# --------------------------------------------------------------
# APlayer settings
# --------------------------------------------------------------
# enabled:  true/false   开启/关闭
# id: song id / playlist id / album id / search keyword   歌曲ID、歌单ID、关键字
# server: netease, tencent, kugou, xiami, baidu     音乐平台
# type: song, playlist, album, search, artist  类型
# auto: music link, support: netease, tencent, xiami
# fixed: true/false   吸底模式
# mini: true/false   迷你模式
# autoplay: true/false   自动播放
# theme: #eeeeee 主题颜色
# loop: values: 'all', 'one', 'none' 循环播放
# order: values: 'list', 'random' 是否随机播放
# preload: values: 'none', 'metadata', 'auto' 预载入
# volume:	0.7	默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
# mutex: true/false	互斥，阻止多个播放器同时播放，当前播放器播放时暂停其他播放器
# list-folded:	true/false	列表默认折叠
# list-max-height:	340px	列表最大高度
# storage-name:	metingjs	存储播放器设置的 localStorage key
aplayer:
  enabled: true
  id: 3099335800
  server: netease
  type: playlist
  auto:
  fixed: true
  mini: true
  autoplay: true
  theme: #607d8b
  loop: 'all'
  order: 'random'
  preload: 'auto'
  volume: 0.7
  mutex: true
  listfolded: true
  listmaxheight: 340px
  storagename: metingjs
  cdn:
    css: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
    js: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    meting: https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js